### ISSUE TITLE
Libreria Vue

### ISSUE THREAD

**Issue by Daniele-Tentoni** [Weather-Vortex/weather-vortex-server#28]
Apro questa issue per segnalare che in questo progetto sono state aggiunte le dipendenze da Vue e Vue Router:
```
"vue": "^2.6.14",
"vue-router": "^3.5.2"
```
Occorre rimuoverle appena possibile quando sarà pronto il client per evitare di creare confusione e mischiare le cose dei due componenti del progetto.

**Comment by silviazandoli** [comment]
ok, cancello quelle dipendenze nel branch che sto facendo delle operazioni crud, così quando mergerà in dev non ci sarà più

**Comment by Daniele-Tentoni** [comment]
@silviazandoli se ti servono ancora puoi lasciarle fino a quando non saremo pronti con il client, questo vuole essere un reminder.

**Comment by silviazandoli** [comment]
ora con il merge di adesso quelle dipendenze non dovrebbero più esserci

**Comment by Daniele-Tentoni** [comment]
Closed by merging #30 .
