### ISSUE TITLE
Refactoring auth routes

### ISSUE THREAD

**Issue by Daniele-Tentoni** [Weather-Vortex/weather-vortex-server#47]
Abbiamo ritenuto necessario cambiare le routes dell'autenticazione perché poco significative. Io proporrei di cambiare da `api` a `auth`. @igor-lirussi e @silviazandoli , se ritenete questa modifica necessaria e la proposta di modifica corretta, commentate con un sì oppure con le vostre proposte di modifica. Dopodiché, potremo iniziare a lavorarci. Vedere la issue corrispondente anche sul client.

**Comment by silviazandoli** [comment]
sì
