### ISSUE TITLE
Route GET feedbacks by user

### ISSUE THREAD

**Issue by Daniele-Tentoni** [Weather-Vortex/weather-vortex-server#59]
Occorre creare una route per ottenere i feedbacks di un utente. Lo schema potrebbe essere `GET /feedbacks/user/:id` dove id è l'Object Id dell'utente. Questa chiamata deve tornare solamente una lista di feedbacks fatti dall'utente specificato. Non deve essere autenticata. Bisogna creare i test automatici necessari dentro al file feedbacks.routes.js per controllare che venga restituito un errore 404 se l'utente non esiste oppure la lista dei feedbacks se l'utente esiste. Non deve dare errore se la lista è vuota.

- [x] Route creata
- [x] Dati recuperati
- [x] Test effettuati

### Altro

- [x] Rimuovere il file user.routes.js

**Comment by Daniele-Tentoni** [comment]
Ho pensato che magari una più corretta route che rispetti la filosofia e la semantica Rest sia:
```
GET /users /:id /feedbacks
```
In questo modo si legge: ottieni degli utenti quello con id specificato da cui prelevi solamente i feedbacks.

Se per voi può andare bene io userei quest'ultima convenzione.

La sintassi usata prima:
```
GET /feedbacks/user/:id
```
Si leggerebbe come: ottieni i feedbacks dell'utente specificato dall'id.

Perché propriamente i feedbacks sarebbero una risorsa interna all'utente e questa route servirebbe proprio da usare dentro alla pagina degli utenti.

**Comment by silviazandoli** [comment]
Per me hai ragione, la prima è la migliore. Ha anche più senso com'è scritta
